apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: tracker-managed-postgres-db
spec:
  workload:
    apiVersion: database.crossplane.io/v1alpha1
    kind: PostgreSQLInstance
    metadata:
      name: app-postgresql
    spec:
      classSelector:
        matchLabels:
          example: "true"
          engine: postgresql
      writeConnectionSecretToRef:
        name: postgresqlconn # to override
      engineVersion: "10.0"
  parameters:
  - name: dbconn
    required: true
    fieldPaths:
    - spec.writeConnectionSecretToRef.name

