---
apiVersion: database.alibaba.crossplane.io/v1alpha1
kind: RDSInstance
metadata:
  name: example
  labels:
    example: "true"
    engine: postgresql
spec:
  forProvider:
    engine: postgresql
    engineVersion: "10.0"
    dbInstanceClass: rds.pg.s1.small
    dbInstanceStorageInGB: 20
    securityIPList: "0.0.0.0/0"
    masterUsername: "test123"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-rds
  providerConfigRef:
    name: default
  deletionPolicy: Delete
